name: etri_rl
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.12=he1021f5_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
    - absl-py==2.3.1
    - ale-py==0.8.1
    - autorom==0.4.2
    - autorom-accept-rom-license==0.6.1
    - box2d==2.3.10
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloudpickle==3.1.2
    - colorama==0.4.6
    - contourpy==1.3.2
    - cycler==0.12.1
    - farama-notifications==0.0.4
    - filelock==3.20.0
    - fonttools==4.60.1
    - fsspec==2025.10.0
    - grpcio==1.76.0
    - gymnasium==0.29.1
    - idna==3.11
    - importlib-resources==6.5.2
    - jinja2==3.1.6
    - kiwisolver==1.4.9
    - markdown==3.10
    - markdown-it-py==4.0.0
    - markupsafe==3.0.3
    - matplotlib==3.10.7
    - mdurl==0.1.2
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==1.26.4
    - opencv-python==4.6.0.66
    - packaging==25.0
    - pandas==2.3.3
    - pillow==12.0.0
    - protobuf==6.33.1
    - psutil==7.1.3
    - pygame==2.6.1
    - pygments==2.19.2
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - requests==2.32.5
    - rich==14.2.0
    - sb3-contrib==2.7.0
    - shimmy==0.2.1
    - six==1.17.0
    - stable-baselines3==2.7.0
    - sympy==1.13.1
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - torch==2.5.1
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - tqdm==4.67.1
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - werkzeug==3.1.3
prefix: C:\Users\anse0\anaconda3\envs\etri_rl
